//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookShopProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bookShopEntities : DbContext
    {
        public bookShopEntities()
            : base("name=bookShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cart> cart { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<userDetails> userDetails { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<books> books { get; set; }
    }
}
